apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ci-cd-demo
  namespace: ci-cd-demo
  labels:
    app.kubernetes.io/name: ci-cd-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ci-cd-demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ci-cd-demo
                port:
                  number: 80
